### ISSUE TITLE
practica 5 marcador Hiro

### ISSUE THREAD

**Issue by DamGL** [SistemasTecTlaxiaco/practica-de-marcador-hiro-equipo-damaris#1]
[practica 5 realidad aumentada con marcador Hiro.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-marcador-hiro-equipo-damaris/files/8604736/practica.5.realidad.aumentada.con.marcador.Hiro.pdf)

**Comment by ThorSampy** [comment]
El reporte esta en forma y  cuenta con los puntos acordados
Calificación 20%

**Comment by josealfredo79** [comment]
bien hecho y revisado...
